USE [KIPP_NJ]
GO

/****** Object:  StoredProcedure [dbo].[spCOURSES_REFRESH]    Script Date: 15.06.2013 17:22:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [dbo].[sp_ps_Courses_refresh]
AS
BEGIN

 DECLARE @sql AS VARCHAR(MAX)='';

 -- Step 1: truncate table
 EXEC('TRUNCATE TABLE dbo.[COURSES]');

 -- Step 2: disable all nonclustered indexes on table
 SELECT @sql = @sql + 
  'ALTER INDEX ' + indexes.name + ' ON  dbo.' + objects.name + ' DISABLE;' +CHAR(13)+CHAR(10)
 FROM 
  sys.indexes
 JOIN 
  sys.objects 
  ON sys.indexes.object_id = sys.objects.object_id
 WHERE sys.indexes.type_desc = 'NONCLUSTERED'
  AND sys.objects.type_desc = 'USER_TABLE'
  AND sys.objects.name = 'COURSES';

 EXEC (@sql);

 -- step 3: insert rows from remote source
 INSERT INTO [dbo].[COURSES]
      ([DCID]
      ,[ID]
      ,[COURSE_NUMBER]
      ,[COURSE_NAME]
      ,[CREDIT_HOURS]
      ,[ADD_TO_GPA]
      ,[CODE]
      ,[PREREQUISITESVALUE]
      ,[SCHOOLID]
      ,[COREQUISITES]
      ,[POWERLINK]
      ,[POWERLINKSPAN]
      ,[REGAVAILABLE]
      ,[REGGRADELEVELS]
      ,[REGTEACHERS]
      ,[TARGETCLASSSIZE]
      ,[MAXCLASSSIZE]
      ,[REGCOURSEGROUP]
      ,[MULTITERM]
      ,[TERMSOFFERED]
      ,[SECTIONSTOOFFER]
      ,[SCHOOLGROUP]
      ,[VOCATIONAL]
      ,[STATUS]
      ,[CREDITTYPE]
      ,[CRHRWEIGHT]
      ,[SCHED_YEAR]
      ,[SCHED_DEPARTMENT]
      ,[SCHED_COURSESUBJECTAREACODE]
      ,[SCHED_FULLCATALOGDESCRIPTION]
      ,[SCHED_COURSEPACKAGE]
      ,[SCHED_COURSEPKGCONTENTS]
      ,[SCHED_SCHEDULED]
      ,[SCHED_SCHEDULETYPECODE]
      ,[SCHED_SECTIONSOFFERED]
      ,[SCHED_TEACHERCOUNT]
      ,[SCHED_PERIODSPERMEETING]
      ,[SCHED_FREQUENCY]
      ,[SCHED_MAXIMUMPERIODSPERDAY]
      ,[SCHED_MINIMUMPERIODSPERDAY]
      ,[SCHED_MAXIMUMDAYSPERCYCLE]
      ,[SCHED_MINIMUMDAYSPERCYCLE]
      ,[SCHED_CONSECUTIVEPERIODS]
      ,[SCHED_BLOCKSTART]
      ,[SCHED_VALIDSTARTPERIODS]
      ,[SCHED_VALIDDAYCOMBINATIONS]
      ,[VALIDEXTRADAYCOMBINATIONS]
      ,[SCHED_EXTRADAYSCHEDULETYPECODE]
      ,[SCHED_LENGTHINNUMBEROFTERMS]
      ,[SCHED_CONSECUTIVETERMS]
      ,[SCHED_BALANCETERMS]
      ,[SCHED_MAXIMUMENROLLMENT]
      ,[SCHED_CONCURRENTFLAG]
      ,[SCHED_FACILITIES]
      ,[SCHED_MULTIPLEROOMS]
      ,[SCHED_LABFLAG]
      ,[SCHED_LABFREQUENCY]
      ,[SCHED_LABPERIODSPERMEETING]
      ,[SCHED_REPEATSALLOWED]
      ,[SCHED_LOADPRIORITY]
      ,[SCHED_LOADTYPE]
      ,[SCHED_SUBSTITUTIONALLOWED]
      ,[SCHED_GLOBALSUBSTITUTION1]
      ,[SCHED_GLOBALSUBSTITUTION2]
      ,[SCHED_GLOBALSUBSTITUTION3]
      ,[SCHED_USEPREESTABLISHEDTEAMS]
      ,[SCHED_CLOSESECTIONAFTERMAX]
      ,[SCHED_USESECTIONTYPES]
      ,[SCHED_BALANCEPRIORITY]
      ,[SCHED_PERIODSPERCYCLE]
      ,[GRADESCALEID]
      ,[GPA_ADDEDVALUE]
      ,[EXCLUDEFROMGPA]
      ,[EXCLUDEFROMCLASSRANK]
      ,[EXCLUDEFROMHONORROLL]
      ,[SCHED_LUNCHCOURSE]
      ,[SCHED_DO_NOT_PRINT]
      ,[EXCLUDE_ADA]
      ,[PROGRAMID]
      ,[EXCLUDEFROMSTOREDGRADES])
 SELECT  CONVERT(INT, DCID) AS DCID,
  CONVERT(INT,ID) AS ID,
  COURSE_NUMBER,
  COURSE_NAME,
  CREDIT_HOURS,
  ADD_TO_GPA,
  CODE,
  PREREQUISITESVALUE,
  CONVERT(INT,SCHOOLID) AS SCHOOLID,
  COREQUISITES,
  POWERLINK,
  POWERLINKSPAN,
  CONVERT(INT,REGAVAILABLE) AS REGAVAILABLE,
  REGGRADELEVELS,
  REGTEACHERS,
  CONVERT(INT,TARGETCLASSSIZE) AS TARGETCLASSSIZE,
  CONVERT(INT,MAXCLASSSIZE) AS MAXCLASSSIZE,
  REGCOURSEGROUP,
  MULTITERM,
  TERMSOFFERED,
  CONVERT(INT,SECTIONSTOOFFER) AS SECTIONSTOOFFER,
  CONVERT(INT,SCHOOLGROUP) AS SCHOOLGROUP,
  CONVERT(INT,VOCATIONAL) AS VOCATIONAL,
  CONVERT(INT,[STATUS]) AS STATUS,
  CREDITTYPE,
  CRHRWEIGHT,
  CONVERT(INT,SCHED_YEAR) AS SCHED_YEAR,
  SCHED_DEPARTMENT,
  SCHED_COURSESUBJECTAREACODE,
  SCHED_FULLCATALOGDESCRIPTION,
  CONVERT(INT,SCHED_COURSEPACKAGE) AS SCHED_COURSEPACKAGE,
  SCHED_COURSEPKGCONTENTS,
  CONVERT(INT,SCHED_SCHEDULED) AS SCHED_SCHEDULED,
  SCHED_SCHEDULETYPECODE,
  CONVERT(INT,SCHED_SECTIONSOFFERED) AS SCHED_SECTIONSOFFERED,
  CONVERT(INT,SCHED_TEACHERCOUNT) AS SCHED_TEACHERCOUNT,
  CONVERT(INT,SCHED_PERIODSPERMEETING) AS SCHED_PERIODSPERMEETING,
  CONVERT(INT,SCHED_FREQUENCY) AS SCHED_FREQUENCY,
  CONVERT(INT,SCHED_MAXIMUMPERIODSPERDAY) AS SCHED_MAXIMUMPERIODSPERDAY,
  CONVERT(INT,SCHED_MINIMUMPERIODSPERDAY) AS SCHED_MINIMUMPERIODSPERDAY,
  CONVERT(INT,SCHED_MAXIMUMDAYSPERCYCLE) AS SCHED_MAXIMUMDAYSPERCYCLE,
  CONVERT(INT,SCHED_MINIMUMDAYSPERCYCLE) AS SCHED_MINIMUMDAYSPERCYCLE,
  CONVERT(INT,SCHED_CONSECUTIVEPERIODS) AS SCHED_CONSECUTIVEPERIODS,
  CONVERT(INT,SCHED_BLOCKSTART) AS SCHED_BLOCKSTART,
  SCHED_VALIDSTARTPERIODS,
  SCHED_VALIDDAYCOMBINATIONS,
  VALIDEXTRADAYCOMBINATIONS,
  SCHED_EXTRADAYSCHEDULETYPECODE,
  CONVERT(INT,SCHED_LENGTHINNUMBEROFTERMS) AS SCHED_LENGTHINNUMBEROFTERMS,
  CONVERT(INT,SCHED_CONSECUTIVETERMS) AS SCHED_CONSECUTIVETERMS,
  CONVERT(INT,SCHED_BALANCETERMS) AS SCHED_BALANCETERMS,
  CONVERT(INT,SCHED_MAXIMUMENROLLMENT) AS SCHED_MAXIMUMENROLLMENT,
  CONVERT(INT,SCHED_CONCURRENTFLAG) AS SCHED_CONCURRENTFLAG,
  SCHED_FACILITIES,
  CONVERT(INT,SCHED_MULTIPLEROOMS) AS SCHED_MULTIPLEROOMS,
  CONVERT(INT,SCHED_LABFLAG) AS SCHED_LABFLAG,
  CONVERT(INT,SCHED_LABFREQUENCY) AS SCHED_LABFREQUENCY,
  CONVERT(INT,SCHED_LABPERIODSPERMEETING) AS SCHED_LABPERIODSPERMEETING,
  CONVERT(INT,SCHED_REPEATSALLOWED) AS SCHED_REPEATSALLOWED,
  CONVERT(INT,SCHED_LOADPRIORITY) AS SCHED_LOADPRIORITY,
  SCHED_LOADTYPE,
  CONVERT(INT,SCHED_SUBSTITUTIONALLOWED) AS SCHED_SUBSTITUTIONALLOWED,
  SCHED_GLOBALSUBSTITUTION1,
  SCHED_GLOBALSUBSTITUTION2,
  SCHED_GLOBALSUBSTITUTION3,
  CONVERT(INT,SCHED_USEPREESTABLISHEDTEAMS) AS SCHED_USEPREESTABLISHEDTEAMS,
  CONVERT(INT,SCHED_CLOSESECTIONAFTERMAX) AS SCHED_CLOSESECTIONAFTERMAX,
  CONVERT(INT,SCHED_USESECTIONTYPES) AS SCHED_USESECTIONTYPES,
  SCHED_BALANCEPRIORITY,
  CONVERT(INT,SCHED_PERIODSPERCYCLE) AS SCHED_PERIODSPERCYCLE,
  CONVERT(INT,GRADESCALEID) AS GRADESCALEID,
  GPA_ADDEDVALUE,
  CONVERT(INT,EXCLUDEFROMGPA) AS EXCLUDEFROMGPA,
  CONVERT(INT,EXCLUDEFROMCLASSRANK) AS EXCLUDEFROMCLASSRANK,
  CONVERT(INT,EXCLUDEFROMHONORROLL) AS EXCLUDEFROMHONORROLL,
  CONVERT(INT,SCHED_LUNCHCOURSE) AS SCHED_LUNCHCOURSE,
  CONVERT(INT,SCHED_DO_NOT_PRINT) AS SCHED_DO_NOT_PRINT,
  CONVERT(INT,EXCLUDE_ADA) AS EXCLUDE_ADA,
  CONVERT(INT,PROGRAMID) AS PROGRAMID,
  CONVERT(INT,EXCLUDEFROMSTOREDGRADES) AS EXCLUDEFROMSTOREDGRADES
 FROM OPENQUERY(PS_TEAM, 'SELECT 
      TO_CHAR(dcid) AS dcid,
      TO_CHAR(ID) AS ID,
      COURSE_NUMBER,
      COURSE_NAME,
      CREDIT_HOURS,
      ADD_TO_GPA,
      CODE,
      DBMS_LOB.SUBSTR(PREREQUISITESVALUE, 2000) AS PREREQUISITESVALUE,
      TO_CHAR(SCHOOLID) AS SCHOOLID,
      DBMS_LOB.SUBSTR(COREQUISITES, 2000) AS COREQUISITES,
      POWERLINK,
      POWERLINKSPAN,
      TO_CHAR(REGAVAILABLE) AS REGAVAILABLE,
      REGGRADELEVELS,
      DBMS_LOB.SUBSTR(REGTEACHERS, 2000) AS REGTEACHERS,
      TO_CHAR(TARGETCLASSSIZE) AS TARGETCLASSSIZE,
      TO_CHAR(MAXCLASSSIZE) AS MAXCLASSSIZE,
      REGCOURSEGROUP,
      MULTITERM,
      DBMS_LOB.SUBSTR(TERMSOFFERED, 2000) AS TERMSOFFERED,
      TO_CHAR(SECTIONSTOOFFER) AS SECTIONSTOOFFER,
      TO_CHAR(SCHOOLGROUP) AS SCHOOLGROUP,
      TO_CHAR(VOCATIONAL) AS VOCATIONAL,
      TO_CHAR(STATUS) AS STATUS,
      CREDITTYPE,
      CRHRWEIGHT,
      TO_CHAR(SCHED_YEAR) AS SCHED_YEAR,
      SCHED_DEPARTMENT,
      SCHED_COURSESUBJECTAREACODE,
      DBMS_LOB.SUBSTR(SCHED_FULLCATALOGDESCRIPTION, 2000) AS SCHED_FULLCATALOGDESCRIPTION,
      TO_CHAR(SCHED_COURSEPACKAGE) AS SCHED_COURSEPACKAGE,
      DBMS_LOB.SUBSTR(SCHED_COURSEPKGCONTENTS, 2000) AS SCHED_COURSEPKGCONTENTS,
      TO_CHAR(SCHED_SCHEDULED) AS SCHED_SCHEDULED,
      SCHED_SCHEDULETYPECODE,
      TO_CHAR(SCHED_SECTIONSOFFERED) AS SCHED_SECTIONSOFFERED,
      TO_CHAR(SCHED_TEACHERCOUNT) AS SCHED_TEACHERCOUNT,
      TO_CHAR(SCHED_PERIODSPERMEETING) AS SCHED_PERIODSPERMEETING,
      TO_CHAR(SCHED_FREQUENCY) AS SCHED_FREQUENCY,
      TO_CHAR(SCHED_MAXIMUMPERIODSPERDAY) AS SCHED_MAXIMUMPERIODSPERDAY,
      TO_CHAR(SCHED_MINIMUMPERIODSPERDAY) AS SCHED_MINIMUMPERIODSPERDAY,
      TO_CHAR(SCHED_MAXIMUMDAYSPERCYCLE) AS SCHED_MAXIMUMDAYSPERCYCLE,
      TO_CHAR(SCHED_MINIMUMDAYSPERCYCLE) AS SCHED_MINIMUMDAYSPERCYCLE,
      TO_CHAR(SCHED_CONSECUTIVEPERIODS) AS SCHED_CONSECUTIVEPERIODS,
      TO_CHAR(SCHED_BLOCKSTART) AS SCHED_BLOCKSTART,
      DBMS_LOB.SUBSTR(SCHED_VALIDSTARTPERIODS, 2000) AS SCHED_VALIDSTARTPERIODS,
      DBMS_LOB.SUBSTR(SCHED_VALIDDAYCOMBINATIONS, 2000) AS SCHED_VALIDDAYCOMBINATIONS,
      DBMS_LOB.SUBSTR(VALIDEXTRADAYCOMBINATIONS, 2000) AS VALIDEXTRADAYCOMBINATIONS,
      SCHED_EXTRADAYSCHEDULETYPECODE,
      TO_CHAR(SCHED_LENGTHINNUMBEROFTERMS) AS SCHED_LENGTHINNUMBEROFTERMS,
      TO_CHAR(SCHED_CONSECUTIVETERMS) AS SCHED_CONSECUTIVETERMS,
      TO_CHAR(SCHED_BALANCETERMS) AS SCHED_BALANCETERMS,
      TO_CHAR(SCHED_MAXIMUMENROLLMENT) AS SCHED_MAXIMUMENROLLMENT,
      TO_CHAR(SCHED_CONCURRENTFLAG) AS SCHED_CONCURRENTFLAG,
      SCHED_FACILITIES,
      TO_CHAR(SCHED_MULTIPLEROOMS) AS SCHED_MULTIPLEROOMS,
      TO_CHAR(SCHED_LABFLAG) AS SCHED_LABFLAG,
      TO_CHAR(SCHED_LABFREQUENCY) AS SCHED_LABFREQUENCY,
      TO_CHAR(SCHED_LABPERIODSPERMEETING) AS SCHED_LABPERIODSPERMEETING,
      TO_CHAR(SCHED_REPEATSALLOWED) AS SCHED_REPEATSALLOWED,
      TO_CHAR(SCHED_LOADPRIORITY) AS SCHED_LOADPRIORITY,
      SCHED_LOADTYPE,
      TO_CHAR(SCHED_SUBSTITUTIONALLOWED) AS SCHED_SUBSTITUTIONALLOWED,
      SCHED_GLOBALSUBSTITUTION1,
      SCHED_GLOBALSUBSTITUTION2,
      SCHED_GLOBALSUBSTITUTION3,
      TO_CHAR(SCHED_USEPREESTABLISHEDTEAMS) AS SCHED_USEPREESTABLISHEDTEAMS,
      TO_CHAR(SCHED_CLOSESECTIONAFTERMAX) AS SCHED_CLOSESECTIONAFTERMAX,
      TO_CHAR(SCHED_USESECTIONTYPES) AS SCHED_USESECTIONTYPES,
      SCHED_BALANCEPRIORITY,
      TO_CHAR(SCHED_PERIODSPERCYCLE) AS SCHED_PERIODSPERCYCLE,
      TO_CHAR(GRADESCALEID) AS GRADESCALEID,
      GPA_ADDEDVALUE,
      TO_CHAR(EXCLUDEFROMGPA) AS EXCLUDEFROMGPA,
      TO_CHAR(EXCLUDEFROMCLASSRANK) AS EXCLUDEFROMCLASSRANK,
      TO_CHAR(EXCLUDEFROMHONORROLL) AS EXCLUDEFROMHONORROLL,
      TO_CHAR(SCHED_LUNCHCOURSE) AS SCHED_LUNCHCOURSE,
      TO_CHAR(SCHED_DO_NOT_PRINT) AS SCHED_DO_NOT_PRINT,
      TO_CHAR(EXCLUDE_ADA) AS EXCLUDE_ADA,
      TO_CHAR(PROGRAMID) AS PROGRAMID,
      TO_CHAR(EXCLUDEFROMSTOREDGRADES) AS EXCLUDEFROMSTOREDGRADES
     FROM COURSES');



 -- Step 4: rebuld all nonclustered indexes on table
 SELECT @sql = @sql + 
  'ALTER INDEX ' + indexes.name + ' ON  dbo.' + objects.name +' REBUILD;' +CHAR(13)+CHAR(10)
 FROM 
  sys.indexes
 JOIN 
  sys.objects 
  ON sys.indexes.object_id = sys.objects.object_id
 WHERE sys.indexes.type_desc = 'NONCLUSTERED'
  AND sys.objects.type_desc = 'USER_TABLE'
  AND sys.objects.name = 'COURSES';

 EXEC (@sql);

END
GO

