USE KIPP_NJ
GO

ALTER VIEW NICOLE$TEST AS 

SELECT S.LASTFIRST
      ,S.STUDENT_NUMBER
      ,CASE
        WHEN S.SCHOOLID = 73252 THEN 'Rise'
        WHEN S.SCHOOLID = 133570965 THEN 'TEAM'        
        ELSE NULL 
       END AS SCHOOL_NAME
      ,S.SCHOOLID
      ,ROUND(AVG(GR.Y1),1) AS AVG_Y1
FROM KIPP_NJ..STUDENTS S WITH(NOLOCK)
LEFT OUTER JOIN KIPP_NJ..GRADES$DETAIL#MS GR WITH(NOLOCK)
  ON S.ID = GR.STUDENTID
WHERE S.GRADE_LEVEL = 5
  AND S.ENROLL_STATUS = 0
GROUP BY S.LASTFIRST
      ,S.STUDENT_NUMBER      
      ,S.SCHOOLID
  --ORDER BY S.ID