USE KIPP_NJ
GO

ALTER VIEW TABLEAU$student_contact_info#wide AS

SELECT   s.ID AS STUDENTID
		,s.student_number
		,cohort.sid
		,s.FAMILY_IDENT

		,cohort.grade_level
		,cohort.schoolid
		,cohort.reporting_schoolid
		,cohort.school_level
		,cohort.school_name

		,cohort.last_name
		,cohort.first_name
		,cohort.lastfirst
		
		,cohort.enroll_status
		,cohort.cohort
		,cohort.entrycode
		,cohort.exitcode
		,cohort.entrydate
		,cohort.exitdate

		,cohort.BOY_status
		,cohort.eoy_status
		
		,cohort.year_in_network
		,cohort.year_in_school

		,cohort.team
		,cohort.advisor
		
		,cohort.gender
		,cohort.ethnicity
		,cohort.dob

		,cohort.SPEDLEP
		,cohort.lep_status

		,cohort.lunchstatus
		,cohort.lunch_app_status
		,cohort.lunch_balance

		,cohort.student_web_id
		,cohort.STUDENT_WEB_PASSWORD

		,CONVERT(VARCHAR(MAX),CONCAT(LTRIM(RTRIM(s.STREET)), ', ', LTRIM(RTRIM(s.CITY)), ' ', LTRIM(RTRIM(s.ZIP)))) AS HOME_NAME           
		,CONVERT(VARCHAR(MAX),con.HOME_PHONE) AS HOME_HOME
		,CONVERT(VARCHAR(MAX),blob.GUARDIANEMAIL) AS HOME_EMAIL
		,CONVERT(VARCHAR(MAX),con.MOTHER) AS PARENT1_NAME
		,CASE WHEN CONCAT(con.mother_home, con.mother_cell, con.mother_day) != '' THEN CONVERT(VARCHAR(MAX),'Mother') END AS PARENT1_RELATION
		,CONVERT(VARCHAR(MAX),con.MOTHER_HOME) AS PARENT1_HOME
		,CONVERT(VARCHAR(MAX),con.MOTHER_CELL) AS PARENT1_CELL
		,CONVERT(VARCHAR(MAX),con.MOTHER_DAY) AS PARENT1_DAY           
		,CONVERT(VARCHAR(MAX),cs.MOTHER_REGISTERED_TO_VOTE) AS PARENT1_REGISTEREDTOVOTE
		,CONVERT(VARCHAR(MAX),blob.GUARDIANEMAIL) AS PARENT1_EMAIL
		,CONVERT(VARCHAR(MAX),con.FATHER) AS PARENT2_NAME             
		,CASE WHEN CONCAT(con.FATHER_HOME, con.FATHER_CELL, con.FATHER_DAY) != '' THEN CONVERT(VARCHAR(MAX),'Father') END AS PARENT2_RELATION
		,CONVERT(VARCHAR(MAX),con.FATHER_HOME) AS PARENT2_HOME
		,CONVERT(VARCHAR(MAX),con.FATHER_CELL) AS PARENT2_CELL
		,CONVERT(VARCHAR(MAX),con.FATHER_DAY) AS PARENT2_DAY
		,CONVERT(VARCHAR(MAX),cs.FATHER_REGISTERED_TO_VOTE) AS PARENT2_REGISTEREDTOVOTE
		,CONVERT(VARCHAR(MAX),blob.GUARDIANEMAIL) AS PARENT2_EMAIL

		,CONVERT(VARCHAR(MAX),con.DOCTOR_NAME) AS DOCTOR_NAME
		,CASE WHEN CONCAT(con.DOCTOR_NAME, con.DOCTOR_PHONE) != '' THEN CONVERT(VARCHAR(MAX),'Doctor') END AS DOCTOR_RELATION
		,CONVERT(VARCHAR(MAX),con.DOCTOR_PHONE) AS DOCTOR_CELL

		,CONVERT(VARCHAR(MAX),con.EMERG_CONTACT_1) AS EMERG1_NAME
		,CONVERT(VARCHAR(MAX),con.EMERG_1_REL) AS EMERG1_RELATION
		,CONVERT(VARCHAR(MAX),con.EMERG_PHONE_1) AS EMERG1_CELL
		,CONVERT(VARCHAR(MAX),con.EMERG_CONTACT_2) AS EMERG2_NAME
		,CONVERT(VARCHAR(MAX),con.EMERG_2_REL) AS EMERG2_RELATION
		,CONVERT(VARCHAR(MAX),con.EMERG_PHONE_2) AS EMERG2_CELL
		,CONVERT(VARCHAR(MAX),con.EMERG_CONTACT_3) AS EMERG3_NAME
		,CONVERT(VARCHAR(MAX),con.EMERG_3_REL) AS EMERG3_RELATION
		,CONVERT(VARCHAR(MAX),con.EMERG_3_PHONE) AS EMERG3_CELL
		,CONVERT(VARCHAR(MAX),con.EMERG_4_NAME) AS EMERG4_NAME
		,CONVERT(VARCHAR(MAX),con.EMERG_4_REL) AS EMERG4_RELATION
		,CONVERT(VARCHAR(MAX),con.EMERG_4_PHONE) AS EMERG4_CELL
		,CONVERT(VARCHAR(MAX),con.EMERG_5_NAME) AS EMERG5_NAME
		,CONVERT(VARCHAR(MAX),con.EMERG_5_REL) AS EMERG5_RELATION
		,CONVERT(VARCHAR(MAX),con.EMERG_5_PHONE) AS EMERG5_CELL

		,CONVERT(VARCHAR(MAX),con.RELEASE_1_NAME) AS RELEASE1_NAME
		,CONVERT(VARCHAR(MAX),con.RELEASE_1_RELATION) AS RELEASE1_RELATION
		,CONVERT(VARCHAR(MAX),con.RELEASE_1_PHONE) AS RELEASE1_CELL
		,CONVERT(VARCHAR(MAX),con.RELEASE_2_NAME) AS RELEASE2_NAME
		,CONVERT(VARCHAR(MAX),con.RELEASE_2_RELATION) AS RELEASE2_RELATION
		,CONVERT(VARCHAR(MAX),con.RELEASE_2_PHONE) AS RELEASE2_CELL
		,CONVERT(VARCHAR(MAX),con.RELEASE_3_NAME) AS RELEASE3_NAME
		,CONVERT(VARCHAR(MAX),con.RELEASE_3_RELATION) AS RELEASE3_RELATION
		,CONVERT(VARCHAR(MAX),con.RELEASE_3_PHONE) AS RELEASE3_CELL
		,CONVERT(VARCHAR(MAX),con.RELEASE_4_NAME) AS RELEASE4_NAME
		,CONVERT(VARCHAR(MAX),con.RELEASE_4_RELATION) AS RELEASE4_RELATION
		,CONVERT(VARCHAR(MAX),con.RELEASE_4_PHONE) AS RELEASE4_CELL           
		,CONVERT(VARCHAR(MAX),con.RELEASE_5_NAME) AS RELEASE5_NAME
		,CONVERT(VARCHAR(MAX),con.RELEASE_5_RELATION) AS RELEASE5_RELATION
		,CONVERT(VARCHAR(MAX),con.RELEASE_5_PHONE) AS RELEASE5_CELL

FROM KIPP_NJ..PS$STUDENTS#static s WITH(NOLOCK)

LEFT OUTER JOIN KIPP_NJ..COHORT$identifiers_long#static cohort WITH(NOLOCK)
ON s.id = cohort.studentid
LEFT OUTER JOIN KIPP_NJ..PS$STUDENTS_custom#static cs WITH(NOLOCK)
ON s.ID = cs.STUDENTID
LEFT OUTER JOIN KIPP_NJ..PS$STUDENTS_contact#static con WITH(NOLOCK)
ON s.ID = con.STUDENTID
LEFT OUTER JOIN KIPP_NJ..PS$STUDENTS_BLObs#static blob WITH(NOLOCK)
ON s.ID = blob.STUDENTID
	
WHERE cohort.year = KIPP_NJ.dbo.fn_Global_Academic_Year()
	AND cohort.rn = 1
	AND cohort.schoolid != 99999
