USE [KIPP_NJ]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

                  
ALTER PROCEDURE [sp_PS$COURSES#static|refresh] AS

BEGIN

  DECLARE @sql AS VARCHAR(MAX)='';

  -- STEP 1: make sure no temp table
		IF OBJECT_ID(N'tempdb..#PS$COURSES#static|refresh') IS NOT NULL
		BEGIN
						DROP TABLE [#PS$COURSES#static|refresh]
		END


  -- STEP 2: load into a temporary staging table.
  SELECT *
		INTO [#PS$COURSES#static|refresh]
  FROM PS$COURSES;
         

  -- STEP 3: truncate destination table
  EXEC('DELETE FROM KIPP_NJ..PS$COURSES#static');


  -- STEP 4: disable all nonclustered indexes on table
  SELECT @sql = @sql + 'ALTER INDEX ' 
                 + indexes.name + ' ON dbo.' 
                 + objects.name + ' DISABLE;' + CHAR(13) + CHAR(10)
  FROM sys.indexes
  JOIN sys.objects 
    ON sys.indexes.object_id = sys.objects.object_id
  WHERE sys.indexes.type_desc = 'NONCLUSTERED'
    AND sys.objects.type_desc = 'USER_TABLE'
    AND sys.objects.name = 'PS$COURSES#static';
  EXEC (@sql);


  -- STEP 5: insert into final destination
  INSERT INTO [PS$COURSES#static]
   (DCID,ID,COURSE_NUMBER,COURSE_NAME,CREDIT_HOURS,ADD_TO_GPA,CODE,PREREQUISITESVALUE,SCHOOLID,COREQUISITES,POWERLINK,POWERLINKSPAN,REGAVAILABLE,REGGRADELEVELS,REGTEACHERS,TARGETCLASSSIZE,MAXCLASSSIZE,REGCOURSEGROUP,MULTITERM,TERMSOFFERED,SECTIONSTOOFFER,SCHOOLGROUP,VOCATIONAL,STATUS,CREDITTYPE,CRHRWEIGHT,SCHED_YEAR,SCHED_DEPARTMENT,SCHED_COURSESUBJECTAREACODE,SCHED_FULLCATALOGDESCRIPTION,SCHED_COURSEPACKAGE,SCHED_COURSEPKGCONTENTS,SCHED_SCHEDULED,SCHED_SCHEDULETYPECODE,SCHED_SECTIONSOFFERED,SCHED_TEACHERCOUNT,SCHED_PERIODSPERMEETING,SCHED_FREQUENCY,SCHED_MAXIMUMPERIODSPERDAY,SCHED_MINIMUMPERIODSPERDAY,SCHED_MAXIMUMDAYSPERCYCLE,SCHED_MINIMUMDAYSPERCYCLE,SCHED_CONSECUTIVEPERIODS,SCHED_BLOCKSTART,SCHED_VALIDSTARTPERIODS,SCHED_VALIDDAYCOMBINATIONS,VALIDEXTRADAYCOMBINATIONS,SCHED_EXTRADAYSCHEDULETYPECODE,SCHED_LENGTHINNUMBEROFTERMS,SCHED_CONSECUTIVETERMS,SCHED_BALANCETERMS,SCHED_MAXIMUMENROLLMENT,SCHED_CONCURRENTFLAG,SCHED_FACILITIES,SCHED_MULTIPLEROOMS,SCHED_LABFLAG,SCHED_LABFREQUENCY,SCHED_LABPERIODSPERMEETING,SCHED_REPEATSALLOWED,SCHED_LOADPRIORITY,SCHED_LOADTYPE,SCHED_SUBSTITUTIONALLOWED,SCHED_GLOBALSUBSTITUTION1,SCHED_GLOBALSUBSTITUTION2,SCHED_GLOBALSUBSTITUTION3,SCHED_USEPREESTABLISHEDTEAMS,SCHED_CLOSESECTIONAFTERMAX,SCHED_USESECTIONTYPES,SCHED_BALANCEPRIORITY,SCHED_PERIODSPERCYCLE,GRADESCALEID,GPA_ADDEDVALUE,EXCLUDEFROMGPA,EXCLUDEFROMCLASSRANK,EXCLUDEFROMHONORROLL,SCHED_LUNCHCOURSE,SCHED_DO_NOT_PRINT,EXCLUDE_ADA,PROGRAMID,EXCLUDEFROMSTOREDGRADES)
  SELECT DCID,ID,COURSE_NUMBER,COURSE_NAME,CREDIT_HOURS,ADD_TO_GPA,CODE,PREREQUISITESVALUE,SCHOOLID,COREQUISITES,POWERLINK,POWERLINKSPAN,REGAVAILABLE,REGGRADELEVELS,REGTEACHERS,TARGETCLASSSIZE,MAXCLASSSIZE,REGCOURSEGROUP,MULTITERM,TERMSOFFERED,SECTIONSTOOFFER,SCHOOLGROUP,VOCATIONAL,STATUS,CREDITTYPE,CRHRWEIGHT,SCHED_YEAR,SCHED_DEPARTMENT,SCHED_COURSESUBJECTAREACODE,SCHED_FULLCATALOGDESCRIPTION,SCHED_COURSEPACKAGE,SCHED_COURSEPKGCONTENTS,SCHED_SCHEDULED,SCHED_SCHEDULETYPECODE,SCHED_SECTIONSOFFERED,SCHED_TEACHERCOUNT,SCHED_PERIODSPERMEETING,SCHED_FREQUENCY,SCHED_MAXIMUMPERIODSPERDAY,SCHED_MINIMUMPERIODSPERDAY,SCHED_MAXIMUMDAYSPERCYCLE,SCHED_MINIMUMDAYSPERCYCLE,SCHED_CONSECUTIVEPERIODS,SCHED_BLOCKSTART,SCHED_VALIDSTARTPERIODS,SCHED_VALIDDAYCOMBINATIONS,VALIDEXTRADAYCOMBINATIONS,SCHED_EXTRADAYSCHEDULETYPECODE,SCHED_LENGTHINNUMBEROFTERMS,SCHED_CONSECUTIVETERMS,SCHED_BALANCETERMS,SCHED_MAXIMUMENROLLMENT,SCHED_CONCURRENTFLAG,SCHED_FACILITIES,SCHED_MULTIPLEROOMS,SCHED_LABFLAG,SCHED_LABFREQUENCY,SCHED_LABPERIODSPERMEETING,SCHED_REPEATSALLOWED,SCHED_LOADPRIORITY,SCHED_LOADTYPE,SCHED_SUBSTITUTIONALLOWED,SCHED_GLOBALSUBSTITUTION1,SCHED_GLOBALSUBSTITUTION2,SCHED_GLOBALSUBSTITUTION3,SCHED_USEPREESTABLISHEDTEAMS,SCHED_CLOSESECTIONAFTERMAX,SCHED_USESECTIONTYPES,SCHED_BALANCEPRIORITY,SCHED_PERIODSPERCYCLE,GRADESCALEID,GPA_ADDEDVALUE,EXCLUDEFROMGPA,EXCLUDEFROMCLASSRANK,EXCLUDEFROMHONORROLL,SCHED_LUNCHCOURSE,SCHED_DO_NOT_PRINT,EXCLUDE_ADA,PROGRAMID,E