USE [KIPP_NJ]
GO

/****** Object:  StoredProcedure [dbo].[spSECTIONS_REFRESH]    Script Date: 15.06.2013 17:22:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [dbo].[sp_PS$SECTIONS_refresh]
AS
BEGIN
 
 BEGIN TRANSACTION
 
DECLARE @sql AS VARCHAR(MAX)='';

 -- Step 1: truncate table
 EXEC('TRUNCATE TABLE dbo.[SECTIONS]');

 -- Step 2: disable all nonclustered indexes on table
 SELECT @sql = @sql + 
  'ALTER INDEX ' + indexes.name + ' ON  dbo.' + objects.name + ' DISABLE;' +CHAR(13)+CHAR(10)
 FROM 
  sys.indexes
 JOIN 
  sys.objects 
  ON sys.indexes.object_id = sys.objects.object_id
 WHERE sys.indexes.type_desc = 'NONCLUSTERED'
  AND sys.objects.type_desc = 'USER_TABLE'
  AND sys.objects.name = 'SECTIONS';

 EXEC (@sql);

 -- step 3: insert rows from remote source
 INSERT INTO [dbo].[SECTIONS]
      ([DCID]
      ,[ID]
      ,[SECTION_NUMBER]
      ,[COURSE_NUMBER]
      ,[TEACHER]
      ,[TERMID]
      ,[PERIOD_OBSOLETE]
      ,[NO_OF_STUDENTS]
      ,[ROOM]
      ,[FASTPERLIST]
      ,[CCRNARRAY]
      ,[ATTENDANCE]
      ,[LASTATTUPDATE]
      ,[SCHOOLID]
      ,[NOOFTERMS]
      ,[TRACKTEACHERATT]
      ,[MAXENROLLMENT]
      ,[DISTUNIQUEID]
      ,[WHERETAUGHT]
      ,[PGFLAGS]
      ,[DAYS_OBSOLETE]
      ,[GRADEPROFILE]
      ,[LOG]
      ,[ROSTERMODSER]
      ,[TEACHERDESCR]
      ,[PGVERSION]
      ,[BLOCKPERIODS_OBSOLETE]
      ,[DEPENDENT_SECS]
      ,[GRADE_LEVEL]
      ,[CAMPUSID]
      ,[EXCLUDE_ADA]
      ,[EXPRESSION]
      ,[GRADESCALEID]
      ,[EXCLUDEFROMGPA]
      ,[BUILDID]
      ,[BITMAP]
      ,[SCHEDULESECTIONID]
      ,[WHERETAUGHTDISTRICT]
      ,[EXCLUDEFROMCLASSRANK]
      ,[EXCLUDEFROMHONORROLL]
      ,[PARENT_SECTION_ID]
      ,[ORIGINAL_EXPRESSION]
      ,[COMMENT_VALUE]
      ,[ATTENDANCE_TYPE_CODE]
      ,[SECTION_TYPE]
      ,[TEAM]
      ,[HOUSE]
      ,[MAXCUT]
      ,[EXCLUDE_STATE_RPT_YN]
      ,[INSTRUCTION_LANG]
      ,[SECTIONINFO_GUID]
      ,[ATT_MODE_CODE]
      ,[SORTORDER]
      ,[PROGRAMID]
      ,[EXCLUDEFROMSTOREDGRADES]
      ,[MAX_LOAD_STATUS])
 SELECT  CONVERT(INT, DCID) AS DCID,
   CONVERT(INT, ID) AS ID,
   SECTION_NUMBER,
   COURSE_NUMBER,
   CONVERT(INT, TEACHER) AS TEACHER,
   CONVERT(INT, TERMID) AS TERMID,
   PERIOD_OBSOLETE,
   CONVERT(INT, NO_OF_STUDENTS) AS NO_OF_STUDENTS,
   ROOM,
   FASTPERLIST,
   CCRNARRAY,
   ATTENDANCE,
   LASTATTUPDATE,
   CONVERT(INT, SCHOOLID) AS SCHOOLID,
   CONVERT(INT, NOOFTERMS) AS NOOFTERMS,
   CONVERT(INT, TRACKTEACHERATT) AS TRACKTEACHERATT,
   CONVERT(INT, MAXENROLLMENT) AS MAXENROLLMENT,
   CONVERT(INT, DISTUNIQUEID) AS DISTUNIQUEID,
   CONVERT(INT, WHERETAUGHT) AS WHERETAUGHT,
   PGFLAGS,
   DAYS_OBSOLETE,
   GRADEPROFILE,
   [LOG],
   CONVERT(INT, ROSTERMODSER) AS ROSTERMODSER,
   TEACHERDESCR,
   CONVERT(INT, PGVERSION) AS PGVERSION,
   BLOCKPERIODS_OBSOLETE,
   DEPENDENT_SECS,
   CONVERT(INT, GRADE_LEVEL) AS GRADE_LEVEL,
   CONVERT(INT, CAMPUSID) AS CAMPUSID,
   CONVERT(INT, EXCLUDE_ADA) AS EXCLUDE_ADA,
   EXPRESSION,
   CONVERT(INT, GRADESCALEID) AS GRADESCALEID,
   CONVERT(INT, EXCLUDEFROMGPA) AS EXCLUDEFROMGPA,
   CONVERT(INT, BUILDID) AS BUILDID,
   BITMAP,
   CONVERT(INT, SCHEDULESECTIONID) AS SCHEDULESECTIONID,
   CONVERT(INT, WHERETAUGHTDISTRICT) AS WHERETAUGHTDISTRICT,
   CONVERT(INT, EXCLUDEFROMCLASSRANK) AS EXCLUDEFROMCLASSRANK,
   CONVERT(INT, EXCLUDEFROMHONORROLL) AS EXCLUDEFROMHONORROLL,
   CONVERT(INT, PARENT_SECTION_ID) AS PARENT_SECTION_ID,
   ORIGINAL_EXPRESSION,
   COMMENT_VALUE,
   CONVERT(INT, ATTENDANCE_TYPE_CODE) AS ATTENDANCE_TYPE_CODE,
   SECTION_TYPE,
   TEAM,
   HOUSE,
   CONVERT(INT, MAXCUT) AS MAXCUT,
   CONVERT(INT, EXCLUDE_STATE_RPT_YN) AS EXCLUDE_STATE_RPT_YN,
   INSTRUCTION_LANG,
   SECTIONINFO_GUID,
   ATT_MODE_CODE,
   CONVERT(INT, SORTORDER) AS SORTORDER,
   CONVERT(INT, PROGRAMID) AS PROGRAMID,
   CONVERT(INT, EXCLUDEFROMSTOREDGRADES) AS EXCLUDEFROMSTOREDGRADES,
   MAX_LOAD_STATUS
 FROM OPENQUERY(PS_TEAM, 'SELECT TO_CHAR(DCID) AS DCID,
           TO_CHAR(ID) AS ID,
           SECTION_NUMBER,
           COURSE_NUMBER,
           TO_CHAR(TEACHER) AS TEACHER,
           TO_CHAR(TERMID) AS TERMID,
           PERIOD_OBSOLETE,
           TO_CHAR(NO_OF_STUDENTS) AS NO_OF_STUDENTS,
           ROOM,
           FASTPERLIST,
           DBMS_LOB.SUBSTR(CCRNARRAY, 2000) AS CCRNARRAY,
           DBMS_LOB.SUBSTR(ATTENDANCE, 2000) AS ATTENDANCE,
           LASTATTUPDATE,
           TO_CHAR(SCHOOLID) AS SCHOOLID,
           TO_CHAR(NOOFTERMS) AS NOOFTERMS,
           TO_CHAR(TRACKTEACHERATT) AS TRACKTEACHERATT,
           TO_CHAR(MAXENROLLMENT) AS MAXENROLLMENT,
           TO_CHAR(DISTUNIQUEID) AS DISTUNIQUEID,
           TO_CHAR(WHERETAUGHT) AS WHERETAUGHT,
           DBMS_LOB.SUBSTR(PGFLAGS, 2000) AS PGFLAGS,
           DAYS_OBSOLETE,
           GRADEPROFILE,
           DBMS_LOB.SUBSTR(LOG, 2000) AS LOG,
           TO_CHAR(ROSTERMODSER) AS ROSTERMODSER,
           DBMS_LOB.SUBSTR(TEACHERDESCR, 2000) AS TEACHERDESCR,
           TO_CHAR(PGVERSION) AS PGVERSION,
           BLOCKPERIODS_OBSOLETE,
           DEPENDENT_SECS,
           TO_CHAR(GRADE_LEVEL) AS GRADE_LEVEL,
           TO_CHAR(CAMPUSID) AS CAMPUSID,
           TO_CHAR(EXCLUDE_ADA) AS EXCLUDE_ADA,
           EXPRESSION,
           TO_CHAR(GRADESCALEID) AS GRADESCALEID,
           TO_CHAR(EXCLUDEFROMGPA) AS EXCLUDEFROMGPA,
           TO_CHAR(BUILDID) AS BUILDID,
           DBMS_LOB.SUBSTR(BITMAP, 2000)  AS BITMAP,
           TO_CHAR(SCHEDULESECTIONID) AS SCHEDULESECTIONID,
           TO_CHAR(WHERETAUGHTDISTRICT) AS WHERETAUGHTDISTRICT,
           TO_CHAR(EXCLUDEFROMCLASSRANK) AS EXCLUDEFROMCLASSRANK,
           TO_CHAR(EXCLUDEFROMHONORROLL) AS EXCLUDEFROMHONORROLL,
           TO_CHAR(PARENT_SECTION_ID) AS PARENT_SECTION_ID,
           ORIGINAL_EXPRESSION,
           DBMS_LOB.SUBSTR(COMMENT_VALUE, 2000) AS COMMENT_VALUE,
           TO_CHAR(ATTENDANCE_TYPE_CODE) AS ATTENDANCE_TYPE_CODE,
           SECTION_TYPE,
           TEAM,
           HOUSE,
           TO_CHAR(MAXCUT) AS MAXCUT,
           TO_CHAR(EXCLUDE_STATE_RPT_YN) AS EXCLUDE_STATE_RPT_YN,
           INSTRUCTION_LANG,
           SECTIONINFO_GUID,
           ATT_MODE_CODE,
           TO_CHAR(SORTORDER) AS SORTORDER,
           TO_CHAR(PROGRAMID) AS PROGRAMID,
           TO_CHAR(EXCLUDEFROMSTOREDGRADES) AS EXCLUDEFROMSTOREDGRADES,
           MAX_LOAD_STATUS
         FROM SECTIONS');

 -- Step 4: rebuld all nonclustered indexes on table
 SELECT @sql = @sql + 
  'ALTER INDEX ' + indexes.name + ' ON  dbo.' + objects.name +' REBUILD;' +CHAR(13)+CHAR(10)
 FROM 
  sys.indexes
 JOIN 
  sys.objects 
  ON sys.indexes.object_id = sys.objects.object_id
 WHERE sys.indexes.type_desc = 'NONCLUSTERED'
  AND sys.objects.type_desc = 'USER_TABLE'
  AND sys.objects.name = 'SECTIONS';

 EXEC (@sql);

--need to commit after insert when this runs in a big Server Agent job
COMMIT TRANSACTION

END

