USE [KIPP_NJ]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

                  
ALTER PROCEDURE [sp_PS$SECTIONS#static|refresh] AS

BEGIN

  DECLARE @sql AS VARCHAR(MAX)='';

  -- STEP 1: make sure no temp table
		IF OBJECT_ID(N'tempdb..#PS$SECTIONS#static|refresh') IS NOT NULL
		BEGIN
						DROP TABLE [#PS$SECTIONS#static|refresh]
		END


  -- STEP 2: load into a temporary staging table.
  SELECT *
		INTO [#PS$SECTIONS#static|refresh]
  FROM PS$SECTIONS;
         

  -- STEP 3: truncate destination table
  EXEC('DELETE FROM KIPP_NJ..PS$SECTIONS#static');


  -- STEP 4: disable all nonclustered indexes on table
  SELECT @sql = @sql + 'ALTER INDEX ' 
                 + indexes.name + ' ON dbo.' 
                 + objects.name + ' DISABLE;' + CHAR(13) + CHAR(10)
  FROM sys.indexes
  JOIN sys.objects 
    ON sys.indexes.object_id = sys.objects.object_id
  WHERE sys.indexes.type_desc = 'NONCLUSTERED'
    AND sys.objects.type_desc = 'USER_TABLE'
    AND sys.objects.name = 'PS$SECTIONS#static';
  EXEC (@sql);


  -- STEP 5: insert into final destination
  INSERT INTO [PS$SECTIONS#static]
   (DCID,ID,SECTION_NUMBER,COURSE_NUMBER,TEACHER,TERMID,PERIOD_OBSOLETE,NO_OF_STUDENTS,ROOM,FASTPERLIST,CCRNARRAY,ATTENDANCE,LASTATTUPDATE,SCHOOLID,NOOFTERMS,TRACKTEACHERATT,MAXENROLLMENT,DISTUNIQUEID,WHERETAUGHT,PGFLAGS,DAYS_OBSOLETE,GRADEPROFILE,LOG,ROSTERMODSER,TEACHERDESCR,PGVERSION,BLOCKPERIODS_OBSOLETE,DEPENDENT_SECS,GRADE_LEVEL,CAMPUSID,EXCLUDE_ADA,EXPRESSION,GRADESCALEID,EXCLUDEFROMGPA,BUILDID,BITMAP,SCHEDULESECTIONID,WHERETAUGHTDISTRICT,EXCLUDEFROMCLASSRANK,EXCLUDEFROMHONORROLL,PARENT_SECTION_ID,ORIGINAL_EXPRESSION,COMMENT_VALUE,ATTENDANCE_TYPE_CODE,SECTION_TYPE,TEAM,HOUSE,MAXCUT,EXCLUDE_STATE_RPT_YN,INSTRUCTION_LANG,SECTIONINFO_GUID,ATT_MODE_CODE,SORTORDER,PROGRAMID,EXCLUDEFROMSTOREDGRADES,MAX_LOAD_STATUS)
  SELECT DCID,ID,SECTION_NUMBER,COURSE_NUMBER,TEACHER,TERMID,PERIOD_OBSOLETE,NO_OF_STUDENTS,ROOM,FASTPERLIST,CCRNARRAY,ATTENDANCE,LASTATTUPDATE,SCHOOLID,NOOFTERMS,TRACKTEACHERATT,MAXENROLLMENT,DISTUNIQUEID,WHERETAUGHT,PGFLAGS,DAYS_OBSOLETE,GRADEPROFILE,LOG,ROSTERMODSER,TEACHERDESCR,PGVERSION,BLOCKPERIODS_OBSOLETE,DEPENDENT_SECS,GRADE_LEVEL,CAMPUSID,EXCLUDE_ADA,EXPRESSION,GRADESCALEID,EXCLUDEFROMGPA,BUILDID,BITMAP,SCHEDULESECTIONID,WHERETAUGHTDISTRICT,EXCLUDEFROMCLASSRANK,EXCLUDEFROMHONORROLL,PARENT_SECTION_ID,ORIGINAL_EXPRESSION,COMMENT_VALUE,ATTENDANCE_TYPE_CODE,SECTION_TYPE,TEAM,HOUSE,MAXCUT,EXCLUDE_STATE_RPT_YN,INSTRUCTION_LANG,SECTIONINFO_GUID,ATT_MODE_CODE,SORTORDER,PROGRAMID,EXCLUDEFROMSTOREDGRADES,MAX_LOAD_STATUS
  FROM [#PS$SECTIONS#static|refresh];
 

  -- STEP 6: rebuld all nonclustered indexes on table
  SELECT @sql = @sql + 'ALTER INDEX ' 
                  + indexes.name + ' ON dbo.' 
                  + objects.name + ' REBUILD;' + CHAR(13) + CHAR(10)
  FROM sys.indexes
  JOIN sys.objects 
    ON sys.indexes.object_id = sys.objects.object_id
  WHERE sys.indexes.type_desc = 'NONCLUSTERED'
    AND sys.objects.type_desc = 'USER_TABLE'
    AND sys.objects.name = 'PS$SECTIONS#static';
  EXEC (@sql);
  
END                  
