USE KIPP_NJ
GO

ALTER PROCEDURE sp_DISC$log#MERGE AS

BEGIN

  WITH log_update AS (
    SELECT DCID
          ,STUDENTID
          ,SCHOOLID
          ,ENTRY_AUTHOR
          ,ENTRY_DATE
          ,DISCIPLINE_INCIDENTDATE
          ,LOGTYPEID
          ,SUBTYPE
          ,SUBJECT
          ,DISCIPLINE_INCIDENTTYPE
          ,DISCIPLINE_ACTIONTAKEN
          ,DISCIPLINE_ACTIONTAKENDETAIL
          ,CONSEQUENCE
    FROM OPENQUERY(PS_TEAM,'
      SELECT dcid
            ,studentid
            ,schoolid
            ,entry_author
            ,SUBSTR(entry_date, 1, 10) AS entry_date
            ,SUBSTR(discipline_incidentdate, 1, 10) AS discipline_incidentdate
            ,logtypeid
            ,subtype
            ,subject          
            ,discipline_incidenttype
            ,Discipline_ActionTaken
            ,Discipline_ActionTakendetail
            ,consequence
      FROM log    
      WHERE (log.entry_date >= TO_DATE(''2014-08-01'',''YYYY-MM-DD'') OR log.discipline_incidentdate >= TO_DATE(''2014-08-01'',''YYYY-MM-DD''))
        AND log.entry_date <= TRUNC(SYSDATE)
    ') disc /*-- UPDATE QUERY FOR CURRENT SCHOOL YEAR --*/
   )

  MERGE KIPP_NJ..DISC$log#STAGING AS TARGET
  USING log_update AS SOURCE
     ON TARGET.DCID = SOURCE.DCID
    AND TARGET.STUDENTID = SOURCE.STUDENTID
    AND TARGET.SCHOOLID = SOURCE.SCHOOLID
  WHEN MATCHED THEN
   UPDATE
    SET TARGET.ENTRY_AUTHOR = SOURCE.ENTRY_AUTHOR
       ,TARGET.ENTRY_DATE = SOURCE.ENTRY_DATE
       ,TARGET.DISCIPLINE_INCIDENTDATE = SOURCE.DISCIPLINE_INCIDENTDATE
       ,TARGET.LOGTYPEID = SOURCE.LOGTYPEID
       ,TARGET.SUBTYPE = SOURCE.SUBTYPE
       ,TARGET.SUBJECT = SOURCE.SUBJECT
       ,TARGET.DISCIPLINE_INCIDENTTYPE = SOURCE.DISCIPLINE_INCIDENTTYPE
       ,TARGET.DISCIPLINE_ACTIONTAKEN = SOURCE.DISCIPLINE_ACTIONTAKEN
       ,TARGET.DISCIPLINE_ACTIONTAKENDETAIL = SOURCE.DISCIPLINE_ACTIONTAKENDETAIL
       ,TARGET.CONSEQUENCE = SOURCE.CONSEQUENCE
  WHEN NOT MATCHED BY TARGET THEN
   INSERT
    (DCID
    ,STUDENTID
    ,SCHOOLID
    ,ENTRY_AUTHOR
    ,ENTRY_DATE
    ,DISCIPLINE_INCIDENTDATE
    ,LOGTYPEID
    ,SUBTYPE
    ,SUBJECT
    ,DISCIPLINE_INCIDENTTYPE
    ,DISCIPLINE_ACTIONTAKEN
    ,DISCIPLINE_ACTIONTAKENDETAIL
    ,CONSEQUENCE)
   VALUES
    (SOURCE.DCID
    ,SOURCE.STUDENTID
    ,SOURCE.SCHOOLID
    ,SOURCE.ENTRY_AUTHOR
    ,SOURCE.ENTRY_DATE
    ,SOURCE.DISCIPLINE_INCIDENTDATE
    ,SOURCE.LOGTYPEID
    ,SOURCE.SUBTYPE
    ,SOURCE.SUBJECT
    ,SOURCE.DISCIPLINE_INCIDENTTYPE
    ,SOURCE.DISCIPLINE_ACTIONTAKEN
    ,SOURCE.DISCIPLINE_ACTIONTAKENDETAIL
    ,SOURCE.CONSEQUENCE)
  WHEN NOT MATCHED BY SOURCE 
   AND (TARGET.entry_date >= CONVERT(DATE,CONCAT(KIPP_NJ.dbo.fn_Global_Academic_Year(), '-08-01')) 
        OR TARGET.discipline_incidentdate >= CONVERT(DATE,CONCAT(KIPP_NJ.dbo.fn_Global_Academic_Year(), '-08-01'))) 
   THEN DELETE;

END 

GO