USE KIPP_NJ
GO

ALTER VIEW ATT_MEM$attendance_counts_long AS

SELECT studentid      
      ,LEFT(field,CHARINDEX('_',field)-1) AS term
      ,SUBSTRING(field,CHARINDEX('_',field)+1,8) AS code      
      ,value
FROM ATT_MEM$attendance_counts WITH(NOLOCK)

UNPIVOT(
  value
  FOR field IN (Y1_A
               ,Y1_AD
               ,Y1_AE
               ,Y1_CR
               ,Y1_CS
               ,Y1_EV
               ,Y1_ISS
               ,Y1_OSS
               ,Y1_T
               ,Y1_T10
               ,Y1_TE
               ,Y1_LE
               ,Y1_LEX
               ,Y1_UNI
               ,Y1_ABS_ALL
               ,Y1_T_ALL
               ,CUR_A
               ,CUR_AD
               ,CUR_AE
               ,CUR_CR
               ,CUR_CS
               ,CUR_EV
               ,CUR_ISS
               ,CUR_OSS
               ,CUR_T
               ,CUR_T10
               ,CUR_TE
               ,CUR_LE
               ,CUR_LEX
               ,CUR_UNI
               ,CUR_ABS_ALL
               ,CUR_T_ALL
               ,RT1_A
               ,RT1_AD
               ,RT1_AE
               ,RT1_CR
               ,RT1_CS
               ,RT1_EV
               ,RT1_ISS
               ,RT1_OSS
               ,RT1_T
               ,RT1_T10
               ,RT1_TE
               ,RT1_LE
               ,RT1_LEX
               ,RT1_UNI
               ,RT1_ABS_ALL
               ,RT1_T_ALL
               ,RT2_A
               ,RT2_AD
               ,RT2_AE
               ,RT2_CR
               ,RT2_CS
               ,RT2_EV
               ,RT2_ISS
               ,RT2_OSS
               ,RT2_T
               ,RT2_T10
               ,RT2_TE
               ,RT2_LE
               ,RT2_LEX
               ,RT2_UNI
               ,RT2_ABS_ALL
               ,RT2_T_ALL
               ,RT3_A
               ,RT3_AD
               ,RT3_AE
               ,RT3_CR
               ,RT3_CS
               ,RT3_EV
               ,RT3_ISS
               ,RT3_OSS
               ,RT3_T
               ,RT3_T10
               ,RT3_TE
               ,RT3_LE
               ,RT3_LEX
               ,RT3_UNI
               ,RT3_ABS_ALL
               ,RT3_T_ALL
               ,RT4_A
               ,RT4_AD
               ,RT4_AE
               ,RT4_CR
               ,RT4_CS
               ,RT4_EV
               ,RT4_ISS
               ,RT4_OSS
               ,RT4_T
               ,RT4_T10
               ,RT4_TE
               ,RT4_LE
               ,RT4_LEX
               ,RT4_UNI
               ,RT4_ABS_ALL
               ,RT4_T_ALL
               ,RT5_A
               ,RT5_AD
               ,RT5_AE
               ,RT5_CR
               ,RT5_CS
               ,RT5_EV
               ,RT5_ISS
               ,RT5_OSS
               ,RT5_T
               ,RT5_T10
               ,RT5_TE
               ,RT5_LE
               ,RT5_LEX
               ,RT5_UNI
               ,RT5_ABS_ALL
               ,RT5_T_ALL
               ,RT6_A
               ,RT6_AD
               ,RT6_AE
               ,RT6_CR
               ,RT6_CS
               ,RT6_EV
               ,RT6_ISS
               ,RT6_OSS
               ,RT6_T
               ,RT6_T10
               ,RT6_TE
               ,RT6_LE
               ,RT6_LEX
               ,RT6_UNI
               ,RT6_ABS_ALL
               ,RT6_T_ALL
               ,CUR_TRIP_ABS
               ,RT1_TRIP_ABS
               ,RT2_TRIP_ABS
               ,RT3_TRIP_ABS
               ,RT4_TRIP_ABS
               ,RT5_TRIP_ABS
               ,RT6_TRIP_ABS
               ,Y1_TRIP_ABS)
 ) u