USE KIPP_NJ
GO

ALTER VIEW PS$STUDENTS_contact AS

SELECT *
FROM OPENQUERY(PS_TEAM,'
  SELECT s.ID AS STUDENTID
        ,s.HOME_PHONE
        ,s.MOTHER
        ,s.FATHER
        ,s.DOCTOR_NAME
        ,s.DOCTOR_PHONE
        ,s.EMERG_CONTACT_1        
        ,s.EMERG_PHONE_1
        ,s.EMERG_CONTACT_2        
        ,s.EMERG_PHONE_2        
        
        ,c.MOTHER_HOME_PHONE AS MOTHER_HOME
        ,c.MOTHERDAYPHONE AS MOTHER_DAY        
        ,c.FATHER_HOME_PHONE AS FATHER_HOME        
        ,c.FATHERDAYPHONE AS FATHER_DAY        
        ,c.EMERG_1_REL AS EMERG_1_REL
        ,c.EMERG_2_REL AS EMERG_2_REL
        ,c.EMERG_CONTACT_3 AS EMERG_CONTACT_3
        ,c.EMERG_3_REL AS EMERG_3_REL
        ,c.EMERG_3_PHONE AS EMERG_3_PHONE
        
        ,u.MOTHER_CELL
        ,u.FATHER_CELL
        ,u.EMERG_4_NAME AS EMERG_4_NAME
        ,u.EMERG_4_REL AS EMERG_4_REL
        ,u.EMERG_4_PHONE AS EMERG_4_PHONE
        ,u.EMERG_5_NAME AS EMERG_5_NAME
        ,u.EMERG_5_REL AS EMERG_5_REL
        ,u.EMERG_5_PHONE AS EMERG_5_PHONE
        ,u.RELEASE_1_NAME AS RELEASE_1_NAME
        ,u.RELEASE_1_PHONE AS RELEASE_1_PHONE
        ,u.RELEASE_1_RELATION AS RELEASE_1_RELATION      
        ,u.RELEASE_2_NAME AS RELEASE_2_NAME
        ,u.RELEASE_2_PHONE AS RELEASE_2_PHONE
        ,u.RELEASE_2_RELATION AS RELEASE_2_RELATION
        ,u.RELEASE_3_NAME AS RELEASE_3_NAME
        ,u.RELEASE_3_PHONE AS RELEASE_3_PHONE
        ,u.RELEASE_3_RELATION AS RELEASE_3_RELATION
        ,u.RELEASE_4_NAME AS RELEASE_4_NAME
        ,u.RELEASE_4_PHONE AS RELEASE_4_PHONE
        ,u.RELEASE_4_RELATION AS RELEASE_4_RELATION
        ,u.RELEASE_5_NAME AS RELEASE_5_NAME
        ,u.RELEASE_5_PHONE AS RELEASE_5_PHONE
        ,u.RELEASE_5_RELATION AS RELEASE_5_RELATION
  FROM STUDENTS s
  JOIN STUDENTCOREFIELDS c
    ON s.DCID = c.STUDENTSDCID
  JOIN U_STUDENTSUSERFIELDS u
    ON s.DCID = u.STUDENTSDCID  
');