USE KIPP_NJ
GO

ALTER VIEW PS$CUSTOM_STUDENTS AS

SELECT *
FROM OPENQUERY(PS_TEAM,'
  SELECT ID AS STUDENTID                
        ,PS_CUSTOMFIELDS.GETCF(''STUDENTS'',ID,''SID'') AS SID
        ,PS_CUSTOMFIELDS.GETCF(''STUDENTS'',ID,''ADVISOR'') AS ADVISOR
        ,PS_CUSTOMFIELDS.GETCF(''STUDENTS'',ID,''ADVISOR_EMAIL'') AS ADVISOR_EMAIL
        ,PS_CUSTOMFIELDS.GETCF(''STUDENTS'',ID,''ADVISOR_CELL'') AS ADVISOR_CELL
        ,PS_CUSTOMFIELDS.GETCF(''STUDENTS'',ID,''SPEDLEP'') AS SPEDLEP
        ,PS_CUSTOMFIELDS.GETCF(''STUDENTS'',ID,''MOTHER_CELL'') AS MOTHER_CELL
        ,PS_CUSTOMFIELDS.GETCF(''STUDENTS'',ID,''MOTHERDAYPHONE'') AS MOTHER_DAY
        ,PS_CUSTOMFIELDS.GETCF(''STUDENTS'',ID,''MOTHER_HOME_PHONE'') AS MOTHER_HOME
        ,PS_CUSTOMFIELDS.GETCF(''STUDENTS'',ID,''FATHER_CELL'') AS FATHER_CELL
        ,PS_CUSTOMFIELDS.GETCF(''STUDENTS'',ID,''FATHERDAYPHONE'') AS FATHER_DAY
        ,PS_CUSTOMFIELDS.GETCF(''STUDENTS'',ID,''FATHER_HOME_PHONE'') AS FATHER_HOME      
        ,PS_CUSTOMFIELDS.GETCF(''STUDENTS'',ID,''LUNCH_STATUS_1213'') AS LUNCH_STATUS_1213
        ,PS_CUSTOMFIELDS.GETCF(''STUDENTS'',ID,''LUNCH_BALANCE'') AS LUNCH_BALANCE
        ,PS_CUSTOMFIELDS.GETCF(''STUDENTS'',ID,''DIYNICKNAME'') AS DIY_NICKNAME
        ,PS_CUSTOMFIELDS.GETCF(''STUDENTS'',ID,''504_STATUS'') AS STATUS_504
        ,PS_CUSTOMFIELDS.GETCF(''STUDENTS'',ID,''SPEDLEP_CODES'') AS SPEDLEP_CODE          
        ,PS_CUSTOMFIELDS.GETCF(''STUDENTS'',ID,''DEFAULT_STUDENT_WEB_ID'') AS DEFAULT_STUDENT_WEB_ID
        ,PS_CUSTOMFIELDS.GETCF(''STUDENTS'',ID,''DEFAULT_STUDENT_WEB_PASSWORD'') AS DEFAULT_STUDENT_WEB_PASSWORD
        ,PS_CUSTOMFIELDS.GETCF(''STUDENTS'',ID,''DEFAULT_FAMILY_WEB_ID'') AS DEFAULT_FAMILY_WEB_ID
        ,PS_CUSTOMFIELDS.GETCF(''STUDENTS'',ID,''DEFAULT_FAMILY_WEB_PASSWORD'') AS DEFAULT_FAMILY_WEB_PASSWORD
        ,PS_CUSTOMFIELDS.GETCF(''STUDENTS'',ID,''MIDDLE_NAME_CUSTOM'') AS MIDDLE_NAME_CUSTOM
        ,PS_CUSTOMFIELDS.GETCF(''STUDENTS'',ID,''LEP_STATUS'') AS LEP_STATUS
        ,PS_CUSTOMFIELDS.GETCF(''STUDENTS'',ID,''NEWARK_ENROLLMENT_NUMBER'') AS NEWARK_ENROLLMENT_NUMBER
  FROM STUDENTS s
')