USE KIPP_NJ
GO

ALTER VIEW PS$STUDENTS_BLObs AS

SELECT *
FROM OPENQUERY(PS_TEAM,'
  SELECT s.ID AS STUDENTID      
        ,TRIM(s.GUARDIANEMAIL) AS GUARDIANEMAIL
        ,TRIM(s.TRANSFERCOMMENT) AS TRANSFERCOMMENT
        ,TRIM(s.EXITCOMMENT) AS EXITCOMMENT
  FROM STUDENTS s
');