USE KIPP_NJ
GO

ALTER VIEW PS$SCHOOLS AS

SELECT *
FROM OPENQUERY(PS_TEAM,'
  SELECT ABBREVIATION
        ,ALTERNATE_SCHOOL_NUMBER
        ,ASSTPRINCIPALEMAIL
        ,ASSTPRINCIPALPHONE
        ,COUNTYNAME
        ,COUNTYNBR
        ,DCID
        ,DFLTNEXTSCHOOL
        ,FEE_EXEMPTION_STATUS
        ,HIGH_GRADE
        ,HIST_HIGH_GRADE
        ,HIST_LOW_GRADE
        ,ID
        ,ISSUMMERSCHOOL
        ,LOW_GRADE
        ,NAME
        ,PRINCIPAL
        ,PRINCIPALEMAIL
        ,PRINCIPALPHONE
        ,PSGUID
        ,SCHEDULEWHICHSCHOOL
        ,SCHOOL_NUMBER
        ,SCHOOLADDRESS
        ,SCHOOLCITY
        ,SCHOOLCOUNTRY
        ,SCHOOLFAX
        ,SCHOOLINFO_GUID
        ,SCHOOLPHONE
        ,SCHOOLSTATE
        ,SCHOOLZIP
        ,SIF_STATEPRID
        ,SORTORDER
        ,STATE_EXCLUDEFROMREPORTING
  FROM SCHOOLS
')