USE KIPP_NJ
GO

ALTER VIEW PS$TEACHERS AS

SELECT *
FROM OPENQUERY(PS_TEAM,'
  SELECT DCID
        ,USERS_DCID
        ,ID
        ,TEACHERNUMBER
        ,LASTFIRST
        ,FIRST_NAME
        ,MIDDLE_NAME
        ,LAST_NAME
        ,NAMEASIMPORTED
        ,HOMESCHOOLID
        ,CANCHANGESCHOOL
        ,SCHOOLID
        ,STATUS
        ,GROUPVALUE
        ,STAFFSTATUS
        ,EMAIL_ADDR
        ,LOGINID
        ,PSACCESS
        ,ADMINLDAPENABLED
        ,TEACHERLOGINID
        ,TEACHERLDAPENABLED
        ,PTACCESS
  FROM TEACHERS
')