USE KIPP_NJ
GO

ALTER VIEW PS$COURSES AS

SELECT *
FROM OPENQUERY(PS_TEAM,'
  SELECT CODE        
        ,COURSE_NAME
        ,COURSE_NUMBER
        ,CREDIT_HOURS
        ,CREDITTYPE
        ,CRHRWEIGHT        
        ,DCID
        ,EXCLUDE_ADA
        ,EXCLUDEFROMCLASSRANK
        ,EXCLUDEFROMGPA
        ,EXCLUDEFROMHONORROLL
        ,EXCLUDEFROMSTOREDGRADES
        ,GPA_ADDEDVALUE
        ,GRADESCALEID
        ,ID
        ,MAXCLASSSIZE
        ,MAXCREDIT        
        ,POWERLINK
        ,POWERLINKSPAN        
        ,PROGRAMID
        ,PSGUID        
        ,SCHED_BALANCEPRIORITY
        ,SCHED_BALANCETERMS        
        ,SCHED_CLOSESECTIONAFTERMAX        
        ,SCHED_CONSECUTIVEPERIODS
        ,SCHED_CONSECUTIVETERMS
        ,SCHED_COURSEPACKAGE        
        ,SCHED_DEPARTMENT
        ,SCHED_DO_NOT_PRINT        
        ,SCHED_FACILITIES
        ,SCHED_FREQUENCY        
        ,SCHED_GLOBALSUBSTITUTION1
        ,SCHED_GLOBALSUBSTITUTION2
        ,SCHED_GLOBALSUBSTITUTION3
        ,SCHED_LABFLAG
        ,SCHED_LABFREQUENCY
        ,SCHED_LABPERIODSPERMEETING
        ,SCHED_LENGTHINNUMBEROFTERMS
        ,SCHED_LOADPRIORITY
        ,SCHED_LOADTYPE
        ,SCHED_LUNCHCOURSE
        ,SCHED_MAXIMUMDAYSPERCYCLE
        ,SCHED_MAXIMUMENROLLMENT
        ,SCHED_MAXIMUMPERIODSPERDAY
        ,SCHED_MINIMUMDAYSPERCYCLE
        ,SCHED_MINIMUMPERIODSPERDAY        
        ,SCHED_PERIODSPERCYCLE
        ,SCHED_PERIODSPERMEETING
        ,SCHED_REPEATSALLOWED
        ,SCHED_SCHEDULED
        ,SCHED_SCHEDULETYPECODE
        ,SCHED_SECTIONSOFFERED
        ,SCHED_SUBSTITUTIONALLOWED
        ,SCHED_TEACHERCOUNT
        ,SCHED_USEPREESTABLISHEDTEAMS
        ,SCHED_USESECTIONTYPES        
        ,SCHOOLID
        ,SECTIONSTOOFFER
        ,STATUS
        ,TARGETCLASSSIZE
        ,TERMSOFFERED
        ,VALIDEXTRADAYCOMBINATIONS
        ,VOCATIONAL
  FROM COURSES
')