USE KIPP_NJ
GO

ALTER VIEW PS$TEACHERS AS

SELECT f.DCID
      ,f.USERS_DCID
      ,f.ID
      ,u.TEACHERNUMBER
      ,u.LASTFIRST
      ,u.FIRST_NAME
      ,u.MIDDLE_NAME
      ,u.LAST_NAME
      ,u.NAMEASIMPORTED
      ,u.HOMESCHOOLID
      ,u.CANCHANGESCHOOL
      ,f.SCHOOLID
      ,f.STATUS
      ,u.GROUPVALUE
      ,f.STAFFSTATUS
      ,u.EMAIL_ADDR
      ,u.LOGINID
      ,u.PSACCESS
      ,u.ADMINLDAPENABLED
      ,u.TEACHERLOGINID
      ,u.TEACHERLDAPENABLED
      ,u.PTACCESS
FROM KIPP_NJ..PS$SCHOOLSTAFF f WITH(NOLOCK)
JOIN KIPP_NJ..PS$USERS#static u WITH(NOLOCK)
  ON f.USERS_DCID = u.DCID