USE KIPP_NJ
GO

ALTER VIEW PS$SCHOOLSTAFF AS

SELECT *
FROM OPENQUERY(PS_TEAM,'
  SELECT BALANCE1
        ,BALANCE2
        ,BALANCE3
        ,BALANCE4
        ,DCID
        ,ID
        ,PSGUID
        ,SCHED_BUILDINGCODE
        ,SCHED_CLASSROOM
        ,SCHED_DEPARTMENT
        ,SCHED_GENDER
        ,SCHED_HOMEROOM
        ,SCHED_HOUSECODE
        ,SCHED_ISTEACHERFREE
        ,SCHED_LUNCH
        ,SCHED_MAXIMUMCONSECUTIVE
        ,SCHED_MAXIMUMCOURSES
        ,SCHED_MAXIMUMFREE
        ,SCHED_MAXPERS
        ,SCHED_MAXPREPS
        ,SCHED_SCHEDULED
        ,SCHED_TEAM
        ,SCHOOLID
        ,STAFFSTATUS
        ,STATUS
        ,USERS_DCID
        ,WHENCREATED
        ,WHENMODIFIED
  FROM SCHOOLSTAFF
')