USE KIPP_NJ
GO

ALTER VIEW PS$TEACHERS AS

SELECT USERS_DCID
      ,DCID
      ,ID
      ,LASTFIRST
      ,FIRST_NAME
      ,MIDDLE_NAME
      ,LAST_NAME
      ,SCHOOLID
      ,STATUS
      ,TITLE
      ,EMAIL_ADDR
      ,PASSWORD
      ,PSACCESS
      ,LOGINID
      ,CLASSPUA
      ,NOOFCURCLASSES
      ,GROUPVALUE
      ,CONVERT(INT,TEACHERNUMBER) AS TEACHERNUMBER
      ,HOME_PHONE
      ,SCHOOL_PHONE
      ,STREET
      ,CITY
      ,STATE
      ,ZIP
      ,PERIODSAVAIL
      ,CANCHANGESCHOOL
      ,LOG
      ,TEACHERLOGINPW
      ,NAMEASIMPORTED
      ,TEACHERLOGINID
      ,TEACHERLOGINIP
      ,STAFFSTATUS
      ,ETHNICITY
      ,ADMINLDAPENABLED
      ,TEACHERLDAPENABLED
      ,SIF_STATEPRID
      ,GRADEBOOKTYPE
      ,HOMESCHOOLID
      ,PTACCESS
FROM OPENQUERY(PS_TEAM,'
  SELECT USERS_DCID
        ,DCID
        ,ID
        ,LASTFIRST
        ,FIRST_NAME
        ,MIDDLE_NAME
        ,LAST_NAME
        ,SCHOOLID
        ,STATUS
        ,TITLE
        ,EMAIL_ADDR
        ,PASSWORD
        ,PSACCESS
        ,LOGINID
        ,CLASSPUA
        ,NOOFCURCLASSES
        ,GROUPVALUE
        ,TEACHERNUMBER
        ,HOME_PHONE
        ,SCHOOL_PHONE
        ,STREET
        ,CITY
        ,STATE
        ,ZIP
        ,PERIODSAVAIL
        ,CANCHANGESCHOOL
        ,LOG
        ,TEACHERLOGINPW
        ,NAMEASIMPORTED
        ,TEACHERLOGINID
        ,TEACHERLOGINIP
        ,STAFFSTATUS
        ,ETHNICITY
        ,ADMINLDAPENABLED
        ,TEACHERLDAPENABLED
        ,SIF_STATEPRID
        ,GRADEBOOKTYPE
        ,HOMESCHOOLID
        ,PTACCESS
  FROM TEACHERS
');