USE KIPP_NJ
GO

ALTER VIEW PS$SECTIONS AS

SELECT *
      ,KIPP_NJ.dbo.fn_TermToYear(TERMID) AS academic_year
FROM OPENQUERY(PS_TEAM,'
  SELECT ATT_MODE_CODE
        ,ATTENDANCE
        ,ATTENDANCE_TYPE_CODE
        ,BLOCKPERIODS_OBSOLETE
        ,BUILDID
        ,CCRNARRAY
        ,COMMENT_VALUE
        ,COURSE_NUMBER
        ,DCID        
        ,DISTUNIQUEID
        ,EXCLUDE_ADA
        ,EXCLUDE_STATE_RPT_YN
        ,EXCLUDEFROMCLASSRANK
        ,EXCLUDEFROMGPA
        ,EXCLUDEFROMHONORROLL
        ,EXCLUDEFROMSTOREDGRADES
        ,EXPRESSION
        ,FASTPERLIST
        ,GRADE_LEVEL
        ,GRADEBOOKTYPE
        ,GRADEPROFILE
        ,GRADESCALEID
        ,HOUSE
        ,ID
        ,INSTRUCTION_LANG
        ,LASTATTUPDATE        
        ,MAX_LOAD_STATUS
        ,MAXCUT
        ,MAXENROLLMENT
        ,NO_OF_STUDENTS
        ,NOOFTERMS
        ,ORIGINAL_EXPRESSION
        ,PARENT_SECTION_ID
        ,PERIOD_OBSOLETE        
        ,PGVERSION
        ,PROGRAMID
        ,PSGUID
        ,ROOM
        ,ROSTERMODSER
        ,SCHEDULESECTIONID
        ,SCHOOLID
        ,SECTION_NUMBER
        ,SECTION_TYPE
        ,SECTIONINFO_GUID
        ,SORTORDER
        ,TEACHER        
        ,TEAM
        ,TERMID
        ,TRACKTEACHERATT
        ,WHERETAUGHT
        ,WHERETAUGHTDISTRICT
  FROM SECTIONS
');