USE [KIPP_NJ]
GO

ALTER VIEW NAVIANCE$college_apps_clean AS

SELECT DISTINCT 
       [navianceid]
      ,[ceeb_code]
      ,[act_code]
      ,[collegename]
      ,[alpha_sort]
      ,[state]
      ,[admissions_fax]
      ,[inst_control]
      ,[level]
      ,[studentid]
      ,[hs_student_id]
      ,[state_student_id]
      ,[last_name]
      ,[first_name]
      ,[middle_name]
      ,[gpa]
      ,[active_student]
      ,[stage]
      ,[class]
      ,[type]
      ,[result_code]
      ,[attending]
      ,[waitlisted]
      ,[deferred]
      ,[date_transcript_requested]
      ,[initial_transcript_sent]
      ,[midyear_transcript_sent]
      ,[final_transcript_sent]
      ,[comments]
      ,[spec]
      ,[award]
      ,[decis]
      ,[leg]
      ,[intv]
      ,[vis]
      ,[urg]
FROM [KIPP_NJ].[dbo].[AUTOLOAD$NAVIANCE_1_college_applications] WITH(NOLOCK)