USE KIPP_NJ
GO

ALTER VIEW SPI$walkthrough_avgs AS

WITH long_data AS (
  SELECT reporting_schoolid AS schoolid
        ,CONCAT(domain, '_', ISNULL(strand,'overall')) AS pivot_field
        ,academic_year
        ,spi_round
        ,ROUND(AVG(score * 100),1) AS avg_score        
  FROM KIPP_NJ..SPI$walkthrough_scores_long WITH(NOLOCK)
  GROUP BY reporting_schoolid
          ,domain          
          ,CUBE(strand)
          ,academic_year
          ,spi_round
 )

SELECT *
      ,ROW_NUMBER() OVER(
         PARTITION BY schoolid, academic_year
           ORDER BY spi_round DESC) AS rn
FROM long_data
PIVOT(
  MAX(avg_score)
  FOR pivot_field IN ([classroom_engagement_environment]
                     ,[classroom_engagement_goalsconnected]
                     ,[classroom_engagement_goalspresent]
                     ,[classroom_engagement_jfactor]
                     ,[classroom_engagement_keymessages]
                     ,[classroom_engagement_peerinteractions]
                     ,[classroom_engagement_studentsengaged]
                     ,[classroom_instruction_checksforunderstanding]
                     ,[classroom_instruction_criteriaforsuccess]
                     ,[classroom_instruction_directions]
                     ,[classroom_instruction_flowpacing]
                     ,[classroom_instruction_goalsconnected]
                     ,[classroom_instruction_objectiveaim]
                     ,[classroom_instruction_questioning]
                     ,[classroom_instruction_ratio]
                     ,[classroom_instruction_rigor]
                     ,[classroom_instructionaldelivery_coldcalls]
                     ,[classroom_instructionaldelivery_criteriaforsuccess]
                     ,[classroom_instructionaldelivery_dailymastery]
                     ,[classroom_instructionaldelivery_discourse]
                     ,[classroom_instructionaldelivery_evidence]
                     ,[classroom_instructionaldelivery_flowpacing]
                     ,[classroom_instructionaldelivery_followupandresponse]
                     ,[classroom_instructionaldelivery_formativecfu]
                     ,[classroom_instructionaldelivery_goalobjective]
                     ,[classroom_instructionaldelivery_gradelevelexpectations]
                     ,[classroom_instructionaldelivery_individual]
                     ,[classroom_instructionaldelivery_masteryawareness]
                     ,[classroom_instructionaldelivery_questionquality]
                     ,[classroom_instructionaldelivery_ratio]
                     ,[classroom_instructionaldelivery_wholeclassfeedback]
                     ,[classroom_management_awareness]
                     ,[classroom_management_effectiveredirectionsstudent]
                     ,[classroom_management_effectiveredirectionsteacher]
                     ,[classroom_management_onehundredpercent]
                     ,[classroom_management_ontask]
                     ,[classroom_management_quietforadults]
                     ,[classroom_management_speedurgency]
                     ,[classroom_management_warmdemanding]
                     ,[classroom_overall]
                     ,[classroom_routinesrules_awareness]
                     ,[classroom_routinesrules_cellphones]
                     ,[classroom_routinesrules_clean]
                     ,[classroom_routinesrules_dresscode]
                     ,[classroom_routinesrules_effectiveredirections]
                     ,[classroom_routinesrules_homework]
                     ,[classroom_routinesrules_onehundredpercent]
                     ,[classroom_routinesrules_ontask]
                     ,[classroom_routinesrules_studentsquietforadults]
                     ,[classroom_routinesrules_transitions]
                     ,[classroom_routinesrules_warmdemanding]
                     ,[classroom_routinesrules_workfast]
                     ,[classroom_routinestransitions_classroomsystems]
                     ,[classroom_routinestransitions_directionsexpectations]
                     ,[classroom_routinestransitions_objectiveaimagenda]
                     ,[classroom_routinestransitions_schoolgradesystems]
                     ,[classroom_routinestransitions_smallgroupblended]
                     ,[classroom_routinestransitions_transitions]
                     ,[culture_arrivaldismissal]
                     ,[culture_bathrooms]
                     ,[culture_celebrations]
                     ,[culture_cell_phones]
                     ,[culture_character]
                     ,[culture_common_spaces]
                     ,[culture_dress_code]
                     ,[culture_engaged]
                     ,[culture_foodgumcandy]
                     ,[culture_hallways]
                     ,[culture_jfactor]
                     ,[culture_main_office]
                     ,[culture_missionvision]
                     ,[culture_overall]
                     ,[culture_quiet_for_adults]
                     ,[culture_respect]
                     ,[culture_schoolculture_arrivaldismissal]
                     ,[culture_schoolculture_bathrooms]
                     ,[culture_schoolculture_celebrations]
                     ,[culture_schoolculture_cellphones]
                     ,[culture_schoolculture_character]
                     ,[culture_schoolculture_commonspaces]
                     ,[culture_schoolculture_dresscode]
                     ,[culture_schoolculture_engaged]
                     ,[culture_schoolculture_foodgumcandy]
                     ,[culture_schoolculture_gumcandy]
                     ,[culture_schoolculture_hallways]
                     ,[culture_schoolculture_jfactor]
                     ,[culture_schoolculture_mainoffice]
                     ,[culture_schoolculture_meals]
                     ,[culture_schoolculture_missionvalues]
                     ,[culture_schoolculture_missionVision]
                     ,[culture_schoolculture_quietforadults]
                     ,[culture_schoolculture_respect]
                     ,[culture_schoolculture_studentwork]
                     ,[culture_schoolculture_transitiontime]
                     ,[culture_student_work]
                     ,[culture_transition_time]
                     ,[student_effective_redirections]
                     ,[student_on_task]
                     ,[student_one_hundred_percent]
                     ,[student_overall]
                     ,[student_peer_interactions]
                     ,[student_quiet_for_adults]
                     ,[student_smallgroupblended]
                     ,[student_speedurgency]
                     ,[student_students_engaged]
                     ,[teacher_awareness]
                     ,[teacher_classroom_systems]
                     ,[teacher_cold_calls]
                     ,[teacher_criteria_for_success]
                     ,[teacher_daily_mastery]
                     ,[teacher_directionsexpectations]
                     ,[teacher_discourse]
                     ,[teacher_effective_redirections]
                     ,[teacher_environment]
                     ,[teacher_evidence]
                     ,[teacher_flowpacing]
                     ,[teacher_followup_and_response]
                     ,[teacher_formative_cfu]
                     ,[teacher_goalobjective]
                     ,[teacher_goals_connected]
                     ,[teacher_grade_level_expectations]
                     ,[teacher_individual]
                     ,[teacher_jfactor]
                     ,[teacher_key_message]
                     ,[teacher_mastery_awareness]
                     ,[teacher_objectiveaimagenda]
                     ,[teacher_overall]
                     ,[teacher_question_quality]
                     ,[teacher_ratio]
                     ,[teacher_schoolgrade_systems]
                     ,[teacher_transitions]
                     ,[teacher_warm_demanding]
                     ,[teacher_wholeclass_feedback])
 ) p